"""Small database boundary for local SQLite and hosted PostgreSQL."""

from __future__ import annotations

import os
import sqlite3
from contextlib import contextmanager
from pathlib import Path
from typing import Any, Iterator


SQLITE_PATH = Path(__file__).resolve().parent / "social_listening.db"


class Database:
    def __init__(self, connection: Any, *, postgres: bool):
        self.connection = connection
        self.postgres = postgres

    def execute(self, query: str, parameters: Any = None) -> Any:
        # App queries use qmark placeholders and contain no literal question marks.
        if self.postgres and parameters is not None:
            query = query.replace("?", "%s")
        if parameters is None:
            return self.connection.execute(query)
        return self.connection.execute(query, parameters)

    def executescript(self, script: str) -> None:
        # This schema contains only simple DDL, without semicolons in SQL strings.
        if self.postgres:
            script = script.replace(
                "INTEGER PRIMARY KEY AUTOINCREMENT",
                "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            ).replace("INTEGER", "BIGINT")
        for statement in script.split(";"):
            if statement.strip():
                self.execute(statement)

    def columns(self, table: str) -> set[str]:
        if table not in {"topics", "posts"}:
            raise ValueError("Unsupported schema table")
        if self.postgres:
            rows = self.execute(
                "SELECT column_name AS name FROM information_schema.columns "
                "WHERE table_schema = current_schema() AND table_name = ?",
                (table,),
            )
        else:
            rows = self.execute(f"PRAGMA table_info({table})")
        return {row["name"] for row in rows}


@contextmanager
def connect_db(
    *, database_url: str | None = None, sqlite_path: Path | None = None,
) -> Iterator[Database]:
    """One transaction per context; always close the connection after it exits."""
    url = os.getenv("DATABASE_URL", "").strip() if database_url is None else database_url
    if url:
        if not url.startswith(("postgres://", "postgresql://")):
            raise RuntimeError("DATABASE_URL must be a PostgreSQL connection string")
        try:
            import psycopg
            from psycopg.rows import dict_row
        except ImportError as error:
            raise RuntimeError("Install PostgreSQL dependencies: pip install -r requirements.txt") from error
        connection = psycopg.connect(url, row_factory=dict_row, connect_timeout=30)
    else:
        path = sqlite_path or Path(os.getenv("SINYALX_DB_PATH") or SQLITE_PATH)
        connection = sqlite3.connect(path, timeout=30)
        connection.row_factory = lambda cursor, row: dict(zip(
            (column[0] for column in cursor.description), row,
        ))
        connection.execute("PRAGMA foreign_keys = ON")
    try:
        with connection:
            yield Database(connection, postgres=bool(url))
    finally:
        connection.close()
